"""empty message

Revision ID: 6e664727f0b5
Revises: bc58a32edba1
Create Date: 2026-08-17 13:48:42.304381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e664727f0b5'
down_revision: Union[str, None] = 'bc58a32edba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('jd_valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'jd_valid')
    # ### end Alembic commands ###
