"""empty message

Revision ID: bc58a32edba1
Revises: 5d6dc22d0593
Create Date: 2026-08-17 13:29:01.409574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc58a32edba1'
down_revision: Union[str, None] = '5d6dc22d0593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('jd_text', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'jd_text')
    # ### end Alembic commands ###
